# Generated by Django 3.2.7 on 2021-10-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fun_fact',
            field=models.TextField(blank=True),
        ),
    ]
