# Generated by Django 3.2.7 on 2021-10-14 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20211014_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='match_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=260), default=list, size=None),
        ),
    ]
