# Generated by Django 3.2.7 on 2021-10-15 06:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_alter_customuser_match_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='num_matches_found',
        ),
        migrations.AddField(
            model_name='customuser',
            name='match_found_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='match_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
    ]
