# Generated by Django 3.2.7 on 2021-10-15 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_alter_customuser_match_found_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='match_found_time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='match_found_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
