# Generated by Django 3.2.7 on 2021-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_auto_20211016_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nft_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
